language: go
sudo: false
go:
  - 1.4
  - tip
addons:
  apt:
    sources:
    - debian-sid
    packages:
    - libsqlite3-dev
install:
- go get github.com/gwenn/yacr
- go get -tags all github.com/gwenn/gosqlite
before_script:
 - go get github.com/bmizerany/assert
script:
 - go test -v -tags all github.com/gwenn/gosqlite